---
- name: Install packages
  hosts: "{{ hosts | default('localhost') }}"
  become: true
  tasks:
    - name: Update
      command: pacman -Syu --noconfirm

    - name: Install packages
      command: |
        pacman -S --noconfirm \
          base-devel \
          git \
          docker \
          docker-compose \
          less \
          ncdu \
          neovim  \
          nodejs \
          npm \
          tmux \
          ttf-firacode-nerd \
          unzip \
          vi \
          vim \
          wget \
          zip \
          zsh \
          alacritty \
          eog \
          firefox \
          noto-fonts-emoji \
          pavucontrol \
          polkit \
          pulseaudio \
          rofi \
          rofi-emoji \
          stow \
          sway \
          swaybg \
          swayidle \
          swaylock \
          thunar \
          vlc \
          waybar \
          wl-clipboard \
          xorg-xwayland
