#cloud-config
# vim: syntax=yaml
# examples:
# https://cloudinit.readthedocs.io/en/latest/topics/examples.html
runcmd:
  - echo "This is from runcmd end"
ssh_pwauth: false
disable_root: true
users:
  - name: ${ssh_username}
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    groups: [users, admin]
    shell: /bin/zsh
    lock_passwd: true
    ssh_authorized_keys:
      - ${ssh_public_key}
growpart:
  mode: auto
  devices: ["/"]
packages:
  - ansible
  - base-devel
  - git
  - less
  - vi
  - vim
  - wget
  - zsh
final_message: "The system is finally up, after $UPTIME seconds"
